[package]
name = "pandora-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pandora-types = { path = "../pandora-types" }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
