[package]
name = "pandora-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pandora"
path = "src/main.rs"

[dependencies]
pandora-harness-coding = { path = "../pandora-harness-coding" }
pandora-provider = { path = "../pandora-provider" }
pandora-runtime = { path = "../pandora-runtime" }
