[package]
name = "pandora-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pandora"
path = "src/main.rs"

[dependencies]
pandora-harnesses = { path = "../pandora-harnesses" }
pandora-provider = { path = "../pandora-provider" }
pandora-runtime = { path = "../pandora-runtime" }
